package org.ramaih.project;

import java.awt.Dimension;
import java.awt.EventQueue;
import java.io.IOException;
import java.nio.file.Paths;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author souradeep
 */
public class MainFrame extends javax.swing.JFrame {

    /**
     * Creates new form MainFrame
     */
    public MainFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbTitle = new javax.swing.JLabel();
        scrPnMain = new javax.swing.JScrollPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMnMovieServices = new javax.swing.JMenu();
        jMnListOfMovies = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        jMnAvailableMovies = new javax.swing.JMenuItem();
        jSeparator2 = new javax.swing.JPopupMenu.Separator();
        jMnMovieOfTheDay = new javax.swing.JMenuItem();
        jMnUserServices = new javax.swing.JMenu();
        jMnLogout = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(400, 300));

        lbTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbTitle.setText("          ");
        getContentPane().add(lbTitle, java.awt.BorderLayout.PAGE_START);

        scrPnMain.setBackground(new java.awt.Color(230, 37, 37));
        scrPnMain.setPreferredSize(new java.awt.Dimension(600, 500));
        getContentPane().add(scrPnMain, java.awt.BorderLayout.CENTER);

        jMnMovieServices.setText("Movie Services");

        jMnListOfMovies.setText("List of movies");
        jMnListOfMovies.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMnListOfMoviesActionPerformed(evt);
            }
        });
        jMnMovieServices.add(jMnListOfMovies);
        jMnMovieServices.add(jSeparator1);

        jMnAvailableMovies.setText("Available movies");
        jMnAvailableMovies.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMnAvailableMoviesActionPerformed(evt);
            }
        });
        jMnMovieServices.add(jMnAvailableMovies);
        jMnMovieServices.add(jSeparator2);

        jMnMovieOfTheDay.setText("Movie of the day");
        jMnMovieOfTheDay.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMnMovieOfTheDayActionPerformed(evt);
            }
        });
        jMnMovieServices.add(jMnMovieOfTheDay);

        jMenuBar1.add(jMnMovieServices);

        jMnUserServices.setText("User Services");

        jMnLogout.setText("Logout");
        jMnLogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMnLogoutActionPerformed(evt);
            }
        });
        jMnUserServices.add(jMnLogout);

        jMenuBar1.add(jMnUserServices);

        setJMenuBar(jMenuBar1);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jMnListOfMoviesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMnListOfMoviesActionPerformed

        lbTitle.setText("Movie List");
        JPanel movieListPanel = new MovieListPanel();
        scrPnMain.setViewportView(movieListPanel);

    }//GEN-LAST:event_jMnListOfMoviesActionPerformed

    private void jMnAvailableMoviesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMnAvailableMoviesActionPerformed

        lbTitle.setText("Available Movies");
        JPanel availableMoviesPanel = new AvailableMoviesPanel(Paths.get("/home/souradeep/Desktop/movieslist"));
        scrPnMain.setViewportView(availableMoviesPanel);
    }//GEN-LAST:event_jMnAvailableMoviesActionPerformed

    private void jMnMovieOfTheDayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMnMovieOfTheDayActionPerformed
        String url = "file:///home/souradeep/Downloads/The Usual Suspects (1995)/The.Usual.Suspects.1995.m720p.mkv";
        String sanitisedUrl = url.replaceAll(" ", "%20");

        String moviePlayerCommand = "vlc ";
        try {
            Runtime.getRuntime().exec(moviePlayerCommand + sanitisedUrl);
        } catch (IOException ex) {
            ex.printStackTrace();
            JOptionPane.showMessageDialog(this, ex.getMessage(), "Error occured", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jMnMovieOfTheDayActionPerformed

    private void jMnLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMnLogoutActionPerformed

        setVisible(false);
        dispose();
        EventQueue.invokeLater(() -> {
            new LoginUser().setVisible(true);
        });

    }//GEN-LAST:event_jMnLogoutActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMnAvailableMovies;
    private javax.swing.JMenuItem jMnListOfMovies;
    private javax.swing.JMenuItem jMnLogout;
    private javax.swing.JMenuItem jMnMovieOfTheDay;
    private javax.swing.JMenu jMnMovieServices;
    private javax.swing.JMenu jMnUserServices;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JPopupMenu.Separator jSeparator2;
    private javax.swing.JLabel lbTitle;
    private javax.swing.JScrollPane scrPnMain;
    // End of variables declaration//GEN-END:variables
}
